# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_weibull <- function(y, a1, a2, c_under) {
    .Call(`_bayesCureRateModel_log_weibull`, y, a1, a2, c_under)
}

complete_log_likelihood_general <- function(y, X, Censoring_status, g, lambda, log_f, log_F, b, I_sim, alpha) {
    .Call(`_bayesCureRateModel_complete_log_likelihood_general`, y, X, Censoring_status, g, lambda, log_f, log_F, b, I_sim, alpha)
}

